### ISSUE TITLE
In juno controller Node :  neutron db-mange issue.

### ISSUE THREAD

**Issue by hpetwal** [enovance/puppet-openstack-cloud#753]
i have created a database using create database neutron;
then granted privileges to it.

i ran the following command 

In Controller Node

	# mysql -u root -p

	> CREATE DATABASE neutron;

	> GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY 'openstack';

	> GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY 'openstack';
	
	> exit

	# source admin-openrc.sh

	# keystone user-create --name neutron --pass openstack

	# keystone user-role-add --user neutron --tenant service --role admin

	# keystone service-create --name neutron --type network --description "OpenStack Networking"

	# keystone endpoint-create --service-id $(keystone service-list | awk '/ network / {print $2}') --publicurl http://controller:9696 --internalurl http://controller:9696 --adminurl http://controller:9696 --region regionOne

	# apt-get install neutron-server neutron-plugin-ml2 python-neutronclient

	# nano /etc/neutron/neutron.conf

	[database]
	...
	connection = mysql://neutron:openstack@controller/neutron

	[DEFAULT]
	...
	rpc_backend = rabbit
	rabbit_host = controller
	rabbit_password = openstack
	...
	auth_strategy = keystone
	...
	verbose = True	
	...
	core_plugin = ml2
	service_plugins = router
	allow_overlapping_ips = True
	...
	notify_nova_on_port_status_changes = True
	notify_nova_on_port_data_changes = True
	nova_url = http://controller:8774/v2
	nova_admin_auth_url = http://controller:35357/v2.0
	nova_region_name = regionOne
	nova_admin_username = nova
	nova_admin_tenant_id = SERVICE_TENANT_ID
	nova_admin_password = openstack

	* Replace SERVICE_TENANT_ID with the service tenant identifier
	* # keystone tenant-get service

	[keystone_authtoken]
	...
	auth_uri = http://controller:5000/v2.0
	identity_uri = http://controller:35357
	admin_tenant_name = service
	admin_user = neutron
	admin_password = openstack

	* Comment out any auth_host, auth_port, and auth_protocol

	# nano /etc/neutron/plugins/ml2/ml2_conf.ini

	[ml2]
	...
	type_drivers = flat,gre
	tenant_network_types = gre
	mechanism_drivers = openvswitch

	[ml2_type_gre]
	...
	tunnel_id_ranges = 1:1000

	[securitygroup]
	...
	enable_security_group = True
	enable_ipset = True
	firewall_driver = neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver

	# nano /etc/nova/nova.conf

	[DEFAULT]
	...
	network_api_class = nova.network.neutronv2.api.API
	security_group_api = neutron
	linuxnet_interface_driver = nova.network.linux_net.
	LinuxOVSInterfaceDriver
	firewall_driver = nova.virt.firewall.NoopFirewallDriver

	[neutron]
	...
	url = http://controller:9696
	auth_strategy = keystone
	admin_auth_url = http://controller:35357/v2.0
	admin_tenant_name = service
	admin_username = neutron
	admin_password = openstack

after that i ran : 

# neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade juno

and got this error : 

no handlers could be found for logger "neutron.common.legacy" Traceback (most recent call last): File ",usr/bin/neutron-db-manage", line 10, in <module> sys.exit(main()) File ",usr/lib/python2.7/dist-packages/neutron/db/migration/cli.py", line 169$ CONF.command.func(config, CONF.command.name) File ",usr/lib/python2.7/dist-packages/neutron/db/migration/cli.py", line 82,$ do_alembic_command(config, cmd, revision, sql=CONF.command.sql) File ",usr/lib/python2.7/dist-packages/neutron/db/migration/cli.py", line 60,$ getattr(alembic_command, cmd)(config, *args, m*kwargs) File ",usr/lib/python2.7/dist-packages/alembic/command.py", line 124, in upgr$ script.run_env() File ",usr/lib/python2.7/dist-packages/alembic/script.py", line 199, in run_e$ util.load_python_file(self.dir, 'env.py.) File ",usr/lib/python2.7/dist-packages/alembic/util.py", line 199, in load_py$ module = load_module(module_id, path) File ",usr/lib/python2.7/dist-packages/alembic/compat.py", line 55, in load_m$ mod = imp.load_source(module_id, path, fp) File ",usr/lib/python2.7/dist-packages/neutron/db/migration/alembic_migration$ importutils.import_class(class_path) File ",usr/lib/python2.7/dist-packages/neutron'openstack/common'importutils.p$ traceback.format_exception(*sys.exc_info()))) ImportError: Class m12 cannot be found (('Traceback (most recent call last):\n'$ 

and in neutron server log : 

WARNING neutron.agent.securitygroups_rpc C-] Driue$ 015-04-15 11:45:07.032 2927 WARNING neutron.api.extensions C-] Extension extra$ 015-04-15 11:45:07.073 2927 WARNING neutron.api.extensions C-] Extension fwaas$ 015-04-15 11:45:07.078 2927 WARNING neutron.api.extensions C-] Extension flauo$ 015-04-15 11:45:07.095 2927 WARNING neutron.api.extensions C-] Extension route$ 015-04-15 11:45:07.100 2927 WARNING neutron.api.extensions C-] Extension ext-g$ 015-04-15 11:45:07.127 2927 WARNING neutron.api.extensions C-] Extension 13_ag$ 015-04-15 11:45:07.166 2927 WARNING neutron.api.extensions C-] Extension lbaas$ 015-04-15 11:45:07.178 2927 WARNING neutron.api.extensions C-] Extension lbaas$ 015-04-15 11:45:07.205 2927 WARNING neutron.api.extensions C-] Extension meter$ 015-04-15 11:45:07.222 2927 WARNING neutron.api.extensions C-] Extension port-$ 015-04-15 11:45:07.255 2927 WARNING neutron.api.extensions C-] Extension route$ 015-04-15 11:45:07.259 2927 WARNING neutron.api.extensions C-] Extension route$ 015-04-15 11:45:07.277 2927 WARNING neutron.api.extensions C-] Extension serui$ 015-04-15 11:45:07.311 2927 WARNING neutron.api.extensions C-] Extension upnaa$ 015-04-15 11:45:07.346 2927 WARNING keystoneclient.middleware.auth_token 1-1 0 015-04-15 11:45:10.989 2927 ERROR neutron.openstack.common.rpc.common C-] AMQP$ 015-04-15 11:45:15.025 2927 ERROR neutron.openstack.common.rpc.common C-] AMQP$ 015-04-15 11:45:21.052 2927 ERROR neutron.openstack.common.rpc.common C-] AMQP$ 015-04-15 11:45:29.079 2927 ERROR neutron.openstack.common.rpc.common C-] AMQP$ 015-04-15 11:45:39.106 2927 ERROR neutron.openstack.common.rpc.common C-] AMQP$ 015-04-15 11:45:51.139 2927 ERROR neutron.openstack.common.rpc.common C-] AMQP$ 015-04-15 11:46:05.173 2927 ERROR neutron.openstack.common.rpc.common C-] AMQP$ 015-04-15 11:46:21.206 2927 ERROR neutron.openstack.common.rpc.common C-] AMQP$ 

further i checked  following list : 
1-  ampq port 5672 is listening..
2- rabbitmq list : containing ampq client and rabbit_amqp1_0
3- rabbitmq startup log

RabbitMQ 3.2.4. Copyright (C) 2007-2013 GoPiuotal, Inc Licensed under the MPL. 
See http://www.rabbitmq.com, 
Logs: /uar/log/rabbitmvrabbitOcontroller.log 
         /uar/log/rabbitouvrabbitOcontroller-sasl.log 
Starting broker... completed with 0 plugins. 

4- checked database..: database neutron exists but not contains any table.

please help me how to resolve the issue.....!
•

**Comment by dsavineau** [comment]
@hpetwal I'm not sure this repository is the right place for your issue because it's not related to puppet-openstack-cloud module.

For your issue you should not use shortname for core_plugin in the neutron configuration file (/etc/neutron/neutron.conf) when using neutron-db-manage
```
- core_plugin = ml2
+ core_plugin = neutron.plugins.ml2.plugin.Ml2Plugin
```
